spring:
  application:
    name: config

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/kshashov/cloud-experiments
          search-paths: configurations

server:
  port: 8052

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8051/eureka/
