spring:
  application:
    name: generator
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false

producer:
  url: http://producer/

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    stream:
      bindings:
        generate-in-0:
          destination: generateTasks

  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 8056

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8051/eureka/

---
spring:
  config:
    activate:
      on-profile: feign
