spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
gateway:
  url: http://localhost:${server.port}

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always

server:
  port: 8053

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8051/eureka/


