spring:
  application:
    name: proxy-producer
  mvc:
    throw-exception-if-no-handler-found: true

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8056

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8051/eureka/

---
spring:
  config:
    activate:
      on-profile: feign
