spring:
  application:
    name: sum
  cloud:
    config:
      uri: http://config/

---
spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8051/eureka/


