spring:
  application:
    name: producer
  mvc:
    throw-exception-if-no-handler-found: true

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    stream:
      bindings:
        output:
          destination: generateTasks
  kafka:
    bootstrap-servers:
      - localhost:9092

server:
  port: 8055

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8051/eureka/
